In [4]:
import pandas as pd
import numpy as np

Question: Créer une nouvelle colonne 'SpendingCategory' (par ex., 'High Spender' si total > 100, 'Regular Spender' sinon) pour chaque membre, puis afficher la distribution de ces catégories par ville.

In [5]:
data = {
    "MemberName": ["Nadia El Amrani", "Hugo Moreau", "Nadia El Amrani", "Chloe Fontaine",
                    "Marc Petit", "Hugo Moreau", "Chloe Fontaine", "Nadia El Amrani",
                    "Marc Petit", "Chloe Fontaine"],
    "City": ["Paris", "Lyon", "Paris", "Marseille",
             "Lyon", "Lyon", "Marseille", "Paris",
             "Lyon", "Marseille"],
    "Amount": [45.0, 60.0, 45.0, 30.0, 75.0, 60.0, 30.0, 45.0, 75.0, 30.0],
    "SessionType": ["Musculation", "Yoga", "Cardio", "Yoga",
                     "Musculation", "Cardio", "Musculation", "Yoga",
                     "Cardio", "Yoga"],
}

df = pd.DataFrame(data)

In [10]:
client_data = df.groupby("MemberName").agg({
    "Amount" : "sum"
})
client_data

                 Amount
MemberName
Chloe Fontaine     90.0
Hugo Moreau       120.0
Marc Petit        150.0
Nadia El Amrani   135.0

In [12]:
client_data['SpendingCategory'] = np.where(client_data['Amount'] > 100 , "High Spender" , "Regular Spender")

In [13]:
client_data

                 Amount SpendingCategory
MemberName
Chloe Fontaine     90.0  Regular Spender
Hugo Moreau       120.0     High Spender
Marc Petit        150.0     High Spender
Nadia El Amrani   135.0     High Spender