In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

** Loading the raw dataset from csv

In [2]:
df = pd.read_csv("../../data/raw/store_data.csv")

** extracting basic infos about the data set as part of data exploration

In [3]:
# general infos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10064 entries, 0 to 10063
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10064 non-null  int64
 1   Order ID       10064 non-null  str
 2   Order Date     10064 non-null  str
 3   Ship Date      9963 non-null   str
 4   Ship Mode      9763 non-null   str
 5   Customer ID    10064 non-null  str
 6   Customer Name  9713 non-null   str
 7   Segment        10064 non-null  str
 8   Country        10064 non-null  str
 9   City           10064 non-null  str
 10  State          10064 non-null  str
 11  Postal Code    9864 non-null   str
 12  Region         10064 non-null  str
 13  Product ID     10064 non-null  str
 14  Category       10064 non-null  str
 15  Sub-Category   10064 non-null  str
 16  Product Name   10064 non-null  str
 17  Sales          9863 non-null   float64
 18  Quantity       9865 non-null   float64
 19  Discount       10064 non-null  float64
 20  Profit         10064 non-null  float64
dtypes: float64(4), int64(1), str(16)
memory usage: 1.6 MB

In [4]:
# a small preview of the dataset :
df.describe()

             Row ID         Sales     Quantity      Discount        Profit
count  10064.000000  9.863000e+03  9865.000000  10064.000000  10064.000000
mean    4994.397059  1.950322e+03     3.780233      0.157501     28.571309
std     2885.848580  4.410673e+04     2.240134      0.210586    233.509461
min        1.000000  4.440000e-01    -5.000000      0.000000  -6599.978000
25%     2496.750000  1.729000e+01     2.000000      0.000000      1.724800
50%     4989.500000  5.450000e+01     3.000000      0.200000      8.643600
75%     7494.250000  2.107600e+02     5.000000      0.200000     29.331600
max     9994.000000  1.131924e+06    14.000000      1.500000   8399.976000

In [5]:
# dimentions
print(f"Dataset dimentions :  {df.shape}")

Dataset dimentions :  (10064, 21)

In [6]:
# first 10 rows of the dataset as a small preview of the data
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7.0,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4.0,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6.0,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3.0,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5.0,0.00,34.4700

In [7]:
# total of missing values in every column of the data set
df.isna().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date        101
Ship Mode        301
Customer ID        0
Customer Name    351
Segment            0
Country            0
City               0
State              0
Postal Code      200
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales            201
Quantity         199
Discount           0
Profit             0
dtype: int64

In [8]:
#percentage of missing values per column :
df.isna().mean() * 100

Row ID           0.000000
Order ID         0.000000
Order Date       0.000000
Ship Date        1.003577
Ship Mode        2.990859
Customer ID      0.000000
Customer Name    3.487679
Segment          0.000000
Country          0.000000
City             0.000000
State            0.000000
Postal Code      1.987281
Region           0.000000
Product ID       0.000000
Category         0.000000
Sub-Category     0.000000
Product Name     0.000000
Sales            1.997218
Quantity         1.977345
Discount         0.000000
Profit           0.000000
dtype: float64

Checking duplicates :

In [9]:
# total duplicated records in the dataset :
df.duplicated().sum()

np.int64(34)

Investigating anomalies and outliers :

In [10]:
shipping_anomalies = df[df['Ship Date'] < df['Order Date']]
print(f"Total anomalies: {len(shipping_anomalies)}")
display(shipping_anomalies[['Order Date', 'Ship Date']])

Total anomalies: 1661

       Order Date   Ship Date
0       11/8/2016  11/11/2016
1       11/8/2016  11/11/2016
5        6/9/2014   6/14/2014
6        6/9/2014   6/14/2014
7        6/9/2014   6/14/2014
...           ...         ...
10042    4/6/2016   4/10/2016
10045  2015-11-24  11/30/2015
10047   12/7/2017  12/12/2017
10051   12/6/2014  12/10/2014
10063    3/8/2015   3/12/2015

[1661 rows x 2 columns]

Products that has negative profit ( losses) :

In [11]:
losing_products = df[df['Profit'] < 0]
losing_products

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
14,15,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5.0,0.80,-123.8580
15,16,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106.0,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3.0,0.80,-3.8160
23,24,US-2017-156909,7/16/2017,7/18/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2.0,0.30,-1.0196
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140.0,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7.0,0.50,-1665.0522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10025,4823,CA-2016-134222,7/10/2016,7/11/2016,Same Day,NZ-18565,NaN,Home Office,United States,YUMA,...,85364.0,West,OFF-BI-10001658,Office Supplies,Binders,GBC Standard Therm-A-Bind Covers,44.8560,6.0,0.70,-35.8848
10031,6743,US-2017-101784,7/6/2017,7/11/2017,Standard Class,PO-18850,NaN,Consumer,United States,Los Angeles,...,90008.0,West,FUR-CH-10001146,Furniture,Chairs,"Global Task Chair, Black",122.1360,3.0,0.20,-13.7403
10032,1878,CA-2017-118885,12/29/2017,1/2/2018,Standard Class,JG-15160,NaN,Consumer,United States,Los Angeles,...,90049.0,West,FUR-CH-10002880,Furniture,Chairs,"Global High-Back Leather Tilter, Burgundy",393.5680,4.0,0.20,-44.2764
10044,871,CA-2016-158099,9/3/2016,9/5/2016,First Class,PK-18910,PAUL KNUTSON,Home Office,United States,Philadelphia,...,19143.0,East,TEC-PH-10002496,Technology,Phones,Cisco SPA301,280.7820,3.0,0.40,-46.7970
10051,5095,US-2014-140452,12/6/2014,12/10/2014,Standard Class,BK-11260,BERENIKE KAMPE,Consumer,United States,Chicago,...,60610.0,Central,FUR-TA-10004086,Furniture,Tables,KI Adjustable-Height Table,214.9500,5.0,0.50,-120.3720

Some money / profit statistics for each category

In [25]:
# here we can see how much each category earned for the business and how many order for each of one of those categories
categories_stats = df.groupby('Category').agg({
    'Profit': 'sum',
    'Order ID' : 'count'
})
# Todo : i noticed here that some of the categories names are duplicated , like "furniture and Furniture" , this needs to be treated later in the data cleaning phase

# 1. Top category in profit
best_category = categories_stats['Profit'].idxmax()
best_profit_val = categories_stats['Profit'].max()
print(f"Top category in profit: {best_category} (£{best_profit_val:,.2f})")

# 2. Worst category in profit
worst_category = categories_stats['Profit'].idxmin()
worst_profit_val = categories_stats['Profit'].min()
print(f"Worst category in profit: {worst_category} (£{worst_profit_val:,.2f})")

# 3. Highest selling category (order volume)
highest_order_category = categories_stats['Order ID'].idxmax()
highest_order_val = categories_stats['Order ID'].max()
print(f"Top category in order volume: {highest_order_category} ({highest_order_val:,} orders)")

# 4. Worst selling category (order volume)
worst_order_category = categories_stats['Order ID'].idxmin()
worst_order_val = categories_stats['Order ID'].min()
print(f"Worst category in order volume: {worst_order_category} ({worst_order_val:,} orders)")

Top category in profit: Technology (£143,463.96)
Worst category in profit: furniture (£56.86)
Top category in order volume: Office Supplies (5,942 orders)
Worst category in order volume: technology (36 orders)

In [28]:
sns.barplot(data=categories_stats.reset_index(), x='', y='Total_Orders')

KeyError: 'Category'